services:
  - type: web
    name: telegram-bot-factory
    runtime: python
    repo: https://github.com/abdalalem11/telegram-bot-factory
    plan: free
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:flask_app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8080
